### ISSUE TITLE
[Bug] AttributeError: 'CompiledStateGraph' object has no attribute 'copy'

### ISSUE THREAD

**Issue by kdenz** [langchain-ai/langgraph-studio#103]
I’ve been facing a recurring error with langgraph-studio. It works fine up to a point, then the error consistently appears. I cloned a new repo and even removed Docker images/volumes, but the issue persists.

langgraph-api: 3.11
Version: 0.0.19
OS: MacOS 14.6.1
OrbStack: 1.7.2

```Running "docker pull langchain/langgraph-api:3.11"
Running "docker image prune -f --filter label=com.docker.compose.project=langgraph-example-cece5fa326b98aa1351d21b9f3ab58dfd4c47b3efdfcaa53622ab0842a026386"
Running "docker image prune -f --filter label=com.docker.compose.project=langgraph-example-cece5fa326b98aa1351d21b9f3ab58dfd4c47b3efdfcaa53622ab0842a026386"
Running "docker compose --project-directory /Users/kmac/dev/langgraph-example --project-name langgraph-example-cece5fa326b98aa1351d21b9f3ab58dfd4c47b3efdfcaa53622ab0842a026386 -f - up --remove-orphans --watch"
3.11: Pulling from langchain/langgraph-api
Digest: sha256:d225aafda7052e629f9a8389190036ba9ebb7e6c4b221b87a2e8109a0cbab207
Status: Image is up to date for langchain/langgraph-api:3.11
docker.io/langchain/langgraph-api:3.11
Total reclaimed space: 0B
Total reclaimed space: 0B
#0 building with "orbstack" instance using docker driver

#1 [langgraph-api internal] load build definition from Dockerfile
#1 transferring dockerfile: 998B done
#1 WARN: JSONArgsRecommended: JSON arguments recommended for CMD to prevent unintended behavior related to OS signals (line 15)
#1 DONE 0.0s

#2 [langgraph-api internal] load metadata for docker.io/langchain/langgraph-api:3.11
#2 DONE 0.0s

#3 [langgraph-api internal] load .dockerignore
#3 transferring context: 2B done
#3 DONE 0.0s

#4 [langgraph-api 1/6] FROM docker.io/langchain/langgraph-api:3.11
#4 DONE 0.0s

#5 [langgraph-api internal] load build context
#5 transferring context: 398B done
#5 DONE 0.0s

#6 [langgraph-api 5/6] RUN set -ex &&     for line in '[project]'                 'name = "my_agent"'                 'version = "0.1"'                 '[tool.setuptools.package-data]'                 '"*" = ["**/*"]'; do         echo "$line" >> /deps/__outer_my_agent/pyproject.toml;     done
#6 CACHED

#7 [langgraph-api 3/6] RUN PYTHONDONTWRITEBYTECODE=1 pip install --no-cache-dir -c /api/constraints.txt -r /deps/__outer_my_agent/my_agent/requirements.txt
#7 CACHED

#8 [langgraph-api 4/6] ADD ./my_agent /deps/__outer_my_agent/my_agent
#8 CACHED

#9 [langgraph-api 2/6] ADD my_agent/requirements.txt /deps/__outer_my_agent/my_agent/requirements.txt
#9 CACHED

#10 [langgraph-api 6/6] RUN PYTHONDONTWRITEBYTECODE=1 pip install --no-cache-dir -c /api/constraints.txt -e /deps/*
#10 CACHED

#11 [langgraph-api] exporting to image
#11 exporting layers done
#11 writing image sha256:872aa694afebc2addd4b746be781db147a19212ebd9998ce1f7c7119743dbfff done
#11 naming to docker.io/library/langgraph-example-cece5fa326b98aa1351d21b9f3ab58dfd4c47b3efdfcaa53622ab0842a026386-langgraph-api done
#11 DONE 0.0s

#12 [langgraph-api] resolving provenance for metadata file
#12 DONE 0.0s
 Network langgraph-example-cece5fa326b98aa1351d21b9f3ab58dfd4c47b3efdfcaa53622ab0842a026386_default  Creating
 Network langgraph-example-cece5fa326b98aa1351d21b9f3ab58dfd4c47b3efdfcaa53622ab0842a026386_default  Created
 Container langgraph-example-cece5fa326b98aa1351d21b9f3ab58dfd4c47b3efdfcaa53622ab0842a026386-langgraph-redis-1  Creating
 Container langgraph-example-cece5fa326b98aa1351d21b9f3ab58dfd4c47b3efdfcaa53622ab0842a026386-langgraph-postgres-1  Creating
 Container langgraph-example-cece5fa326b98aa1351d21b9f3ab58dfd4c47b3efdfcaa53622ab0842a026386-langgraph-redis-1  Created
 Container langgraph-example-cece5fa326b98aa1351d21b9f3ab58dfd4c47b3efdfcaa53622ab0842a026386-langgraph-postgres-1  Created
 Container langgraph-example-cece5fa326b98aa1351d21b9f3ab58dfd4c47b3efdfcaa53622ab0842a026386-langgraph-api-1  Creating
 Container langgraph-example-cece5fa326b98aa1351d21b9f3ab58dfd4c47b3efdfcaa53622ab0842a026386-langgraph-api-1  Created
Attaching to langgraph-api-1, langgraph-postgres-1, langgraph-redis-1
                      ⦿ Watch enabled
langgraph-postgres-1  | 
langgraph-postgres-1  | PostgreSQL Database directory appears to contain a database; Skipping initialization
langgraph-postgres-1  | 
langgraph-redis-1     | 1:C 06 Sep 2024 03:26:22.681 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
langgraph-redis-1     | 1:C 06 Sep 2024 03:26:22.682 # Redis version=6.2.14, bits=64, commit=00000000, modified=0, pid=1, just started
langgraph-redis-1     | 1:C 06 Sep 2024 03:26:22.682 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
langgraph-redis-1     | 1:M 06 Sep 2024 03:26:22.682 * monotonic clock: POSIX clock_gettime
langgraph-redis-1     | 1:M 06 Sep 2024 03:26:22.682 * Running mode=standalone, port=6379.
langgraph-redis-1     | 1:M 06 Sep 2024 03:26:22.682 # Server initialized
langgraph-redis-1     | 1:M 06 Sep 2024 03:26:22.684 * Ready to accept connections
langgraph-postgres-1  | 2024-09-06 03:26:22.785 UTC [1] LOG:  starting PostgreSQL 16.4 (Debian 16.4-1.pgdg120+1) on aarch64-unknown-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
langgraph-postgres-1  | 2024-09-06 03:26:22.786 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
langgraph-postgres-1  | 2024-09-06 03:26:22.786 UTC [1] LOG:  listening on IPv6 address "::", port 5432
langgraph-postgres-1  | 2024-09-06 03:26:22.789 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
langgraph-postgres-1  | 2024-09-06 03:26:22.795 UTC [29] LOG:  database system was shut down at 2024-09-06 03:24:00 UTC
langgraph-postgres-1  | 2024-09-06 03:26:22.808 UTC [1] LOG:  database system is ready to accept connections
langgraph-api-1       | info | Will watch for changes in these directories: ['/deps/__outer_my_agent/my_agent']
langgraph-api-1       | info | Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
langgraph-api-1       | info | Started reloader process [1] using StatReload
langgraph-api-1       | info | Started server process [8]
langgraph-api-1       | info | Waiting for application startup.
langgraph-api-1       | warning | No license key found, running in test mode with LangSmith API key. For production use, set LANGGRAPH_CLOUD_LICENSE_KEY in environment.
langgraph-api-1       | info | HTTP Request: GET https://api.smith.langchain.com/auth?langgraph-api=true "HTTP/1.1 200 OK"
langgraph-api-1       | info | Registering graph with id 'agent'
langgraph-api-1       | info | Starting 10 background workers
langgraph-api-1       | info | Application startup complete.
langgraph-api-1       | info | POST /assistants/search 200 130ms
langgraph-api-1       | error | Exception in ASGI application
 |   + Exception Group Traceback (most recent call last):
  |   File "/usr/local/lib/python3.11/site-packages/starlette/_utils.py", line 77, in collapse_excgroups
  |     yield
  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 186, in __call__
  |     async with anyio.create_task_group() as task_group:
  |   File "/usr/local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 680, in __aexit__
  |     raise BaseExceptionGroup(
  | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 401, in run_asgi
    |     result = await app(  # type: ignore[func-returns-value]
    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
    |     return await self.app(scope, receive, send)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 113, in __call__
    |     await self.middleware_stack(scope, receive, send)
    |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 187, in __call__
    |     raise exc
    |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 165, in __call__
    |     await self.app(scope, receive, _send)
    |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 93, in __call__
    |     await self.simple_response(scope, receive, send, request_headers=headers)
    |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 144, in simple_response
    |     await self.app(scope, receive, send)
    |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 185, in __call__
    |     with collapse_excgroups():
    |   File "/usr/local/lib/python3.11/contextlib.py", line 158, in __exit__
    |     self.gen.throw(typ, value, traceback)
    |   File "/usr/local/lib/python3.11/site-packages/starlette/_utils.py", line 83, in collapse_excgroups
    |     raise exc
    |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 187, in __call__
    |     response = await self.dispatch_func(request, call_next)
    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/local/lib/python3.11/site-packages/langgraph_license/middleware.py", line 26, in dispatch
    |     response = await call_next(request)
    |                ^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 163, in call_next
    |     raise app_exc
    |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 149, in coro
    |     await self.app(scope, receive_or_disconnect, send_no_error)
    |   File "/api/langgraph_api/shared/http_logger.py", line 39, in __call__
    |   File "/api/langgraph_api/shared/http_logger.py", line 33, in __call__
    |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
    |   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
    |     raise exc
    |   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
    |     await app(scope, receive, sender)
    |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 715, in __call__
    |     await self.middleware_stack(scope, receive, send)
    |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 735, in app
    |     await route.handle(scope, receive, send)
    |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 460, in handle
    |     await self.app(scope, receive, send)
    |   File "/api/langgraph_api/auth/middleware.py", line 36, in __call__
    |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/authentication.py", line 48, in __call__
    |     await self.app(scope, receive, send)
    |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 715, in __call__
    |     await self.middleware_stack(scope, receive, send)
    |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 735, in app
    |     await route.handle(scope, receive, send)
    |   File "/api/langgraph_api/shared/route.py", line 120, in handle
    |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 288, in handle
    |     await self.app(scope, receive, send)
    |   File "/api/langgraph_api/shared/route.py", line 37, in app
    |   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
    |     raise exc
    |   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
    |     await app(scope, receive, sender)
    |   File "/api/langgraph_api/shared/route.py", line 32, in app
    |   File "/usr/local/lib/python3.11/site-packages/langgraph_storage/retry.py", line 27, in wrapper
    |     return await func(*args, **kwargs)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/api/langgraph_api/api/assistants.py", line 94, in get_assistant_graph
    |   File "/api/langgraph_api/shared/graph.py", line 87, in get_graph
    | AttributeError: 'CompiledStateGraph' object has no attribute 'copy'
    +------------------------------------```

**Comment by kdenz** [comment]
Changing langgraph-api from 3.11 to 3.12 worked, which is wierd.

**Comment by dqbd** [comment]
Should be fixed with latest API image. Please try restarting the project, which should pull the latest 3.11 / 3.12 image
