### ISSUE TITLE
Getting Error: Failed to load graph: graph is nullush

### ISSUE THREAD

**Issue by nim442** [langchain-ai/langgraph-studio#144]
Getting the following error when trying to execute a graph.
```
Failed to start project components
Application startup failed. Exiting. Reason: Error: Failed to load graph: graph is nullush
    at <anonymous> (/api/langgraph_api/js/client.mts:104:27)
    at <anonymous> (/api/langgraph_api/js/client.mts:110:7)
    at async Promise.all (index 0)
    at async registerFromEnv (/api/langgraph_api/js/client.mts:62:3)
    at async client (/api/langgraph_api/js/client.mts:336:3)
```

Here are the files:
agent.ts
```typescript
import { AIMessage, BaseMessage, HumanMessage } from "@langchain/core/messages";
import { tool } from "@langchain/core/tools";
import { z } from "zod";
import { ChatAnthropic } from "@langchain/anthropic";
import { StateGraph } from "@langchain/langgraph";
import { MemorySaver, Annotation } from "@langchain/langgraph";
import { ToolNode } from "@langchain/langgraph/prebuilt";

// Define the graph state
// See here for more info: https://langchain-ai.github.io/langgraphjs/how-tos/define-state/
const StateAnnotation = Annotation.Root({
  messages: Annotation<BaseMessage[]>({
    reducer: (x, y) => x.concat(y),
  }),
});

// Define the tools for the agent to use
const weatherTool = tool(
  async ({ query }) => {
    // This is a placeholder for the actual implementation
    if (
      query.toLowerCase().includes("sf") ||
      query.toLowerCase().includes("san francisco")
    ) {
      return "It's 60 degrees and foggy.";
    }
    return "It's 90 degrees and sunny.";
  },
  {
    name: "weather",
    description: "Call to get the current weather for a location.",
    schema: z.object({
      query: z.string().describe("The query to use in your search."),
    }),
  }
);

const tools = [weatherTool];
const toolNode = new ToolNode(tools);

const model = new ChatAnthropic({
  model: "claude-3-5-sonnet-20240620",
  temperature: 0,
}).bindTools(tools);

// Define the function that determines whether to continue or not
// We can extract the state typing via `StateAnnotation.State`
function shouldContinue(state: typeof StateAnnotation.State) {
  const messages = state.messages;
  const lastMessage = messages[messages.length - 1] as AIMessage;

  // If the LLM makes a tool call, then we route to the "tools" node
  if (lastMessage.tool_calls?.length) {
    return "tools";
  }
  // Otherwise, we stop (reply to the user)
  return "__end__";
}

// Define the function that calls the model
async function callModel(state: typeof StateAnnotation.State) {
  const messages = state.messages;
  const response = await model.invoke(messages);

  // We return a list, because this will get added to the existing list
  return { messages: [response] };
}
export const ConfigurationSchema = Annotation.Root({
  /**
   * The system prompt to be used by the agent.
   */
  systemPromptTemplate: Annotation<string>,

  /**
   *
   * The name of the language model to be used by the agent.
   */
  model: Annotation<string>,
});
// Define a new graph
const workflow = new StateGraph(StateAnnotation, ConfigurationSchema)
  .addNode("agent", callModel)
  .addNode("tools", toolNode)
  .addEdge("__start__", "agent")
  .addConditionalEdges("agent", shouldContinue)
  .addEdge("tools", "agent");

// Initialize memory to persist state between graph runs
const checkpointer = new MemorySaver();

// Finally, we compile it!
// This compiles it into a LangChain Runnable.
// Note that we're (optionally) passing the memory when compiling the graph
const app = workflow.compile({ checkpointer });
```
langgraph.json
```json
{
  "dockerfile_lines": ["RUN npm config set legacy-peer-deps=true"],
  "graphs": {
    "agent": "./src/LangGraphAgents/testAgent.ts:app"
  },

  "env": ".env",
  "node_version": "20"
}
```

**Comment by dqbd** [comment]
Hello! It does seem like you haven't exported the `app` from the `testAgent.ts` file.  This should be the result:

```
export const app = workflow.compile({ checkpointer });
```
