### ISSUE TITLE
Error editing the state of a graph: Minified React error #31

### ISSUE THREAD

**Issue by ericbellet** [langchain-ai/langgraph-studio#160]
I tried to modify the state from the UI:
<img width="560" alt="Screenshot 2024-10-12 at 13 33 46" src="https://github.com/user-attachments/assets/5d2f0571-c870-4b2a-afed-6ecc9d734f04">
But when I clicked on the **Optional** text
<img width="560" alt="Screenshot 2024-10-12 at 13 33 58" src="https://github.com/user-attachments/assets/cdffa112-fd6a-41e0-b043-504f04364e67">

I got this error:
<img width="1728" alt="Screenshot 2024-10-12 at 13 34 06" src="https://github.com/user-attachments/assets/bbc799bd-d329-4eb2-be44-2b000e9cac45">

Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Bdatabase%2C%20sql_query%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at zl (app://./assets/index-dFph29qp.js:34:57148)
    at h (app://./assets/index-dFph29qp.js:34:58936)
    at S (app://./assets/index-dFph29qp.js:34:60089)
    at g (app://./assets/index-dFph29qp.js:34:62176)
    at nt (app://./assets/index-dFph29qp.js:34:73892)
    at Eh (app://./assets/index-dFph29qp.js:34:118065)
    at xh (app://./assets/index-dFph29qp.js:34:112129)
    at Kg (app://./assets/index-dFph29qp.js:34:112057)
    at Di (app://./assets/index-dFph29qp.js:34:111911)
    at Ws (app://./assets/index-dFph29qp.js:34:108287)

**Comment by dqbd** [comment]
Should be solved with 0.0.31, please let me know if the issue persists.
