### ISSUE TITLE
langgraph-api-1 exited with code 1

### ISSUE THREAD

**Issue by simadimonyan** [langchain-ai/langgraph-studio#189]
```logs
2024-11-12 21:58:28 Traceback (most recent call last):
2024-11-12 21:58:28   File "/usr/local/bin/uvicorn", line 8, in <module>
2024-11-12 21:58:28     sys.exit(main())
2024-11-12 21:58:28              ^^^^^^
2024-11-12 21:58:28   File "/usr/local/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
2024-11-12 21:58:28     return self.main(*args, **kwargs)
2024-11-12 21:58:28            ^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-12 21:58:28   File "/usr/local/lib/python3.12/site-packages/click/core.py", line 1078, in main
2024-11-12 21:58:28     rv = self.invoke(ctx)
2024-11-12 21:58:28          ^^^^^^^^^^^^^^^^
2024-11-12 21:58:28   File "/usr/local/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
2024-11-12 21:58:28     return ctx.invoke(self.callback, **ctx.params)
2024-11-12 21:58:28            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-12 21:58:28   File "/usr/local/lib/python3.12/site-packages/click/core.py", line 783, in invoke
2024-11-12 21:58:28     return __callback(*args, **kwargs)
2024-11-12 21:58:28            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-12 21:58:28   File "/usr/local/lib/python3.12/site-packages/uvicorn/main.py", line 412, in main
2024-11-12 21:58:28     run(
2024-11-12 21:58:28   File "/usr/local/lib/python3.12/site-packages/uvicorn/main.py", line 516, in run
2024-11-12 21:58:28     config = Config(
2024-11-12 21:58:28              ^^^^^^^
2024-11-12 21:58:28   File "/usr/local/lib/python3.12/site-packages/uvicorn/config.py", line 273, in __init__
2024-11-12 21:58:28     self.configure_logging()
2024-11-12 21:58:28   File "/usr/local/lib/python3.12/site-packages/uvicorn/config.py", line 368, in configure_logging
2024-11-12 21:58:28     loaded_config = json.load(file)
2024-11-12 21:58:28                     ^^^^^^^^^^^^^^^
2024-11-12 21:58:28   File "/usr/local/lib/python3.12/json/__init__.py", line 293, in load
2024-11-12 21:58:28     return loads(fp.read(),
2024-11-12 21:58:28            ^^^^^^^^^^^^^^^^
2024-11-12 21:58:28   File "/usr/local/lib/python3.12/json/__init__.py", line 346, in loads
2024-11-12 21:58:28     return _default_decoder.decode(s)
2024-11-12 21:58:28            ^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-12 21:58:28   File "/usr/local/lib/python3.12/json/decoder.py", line 337, in decode
2024-11-12 21:58:28     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
2024-11-12 21:58:28                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-12 21:58:28   File "/usr/local/lib/python3.12/json/decoder.py", line 355, in raw_decode
2024-11-12 21:58:28     raise JSONDecodeError("Expecting value", s, err.value) from None
2024-11-12 21:58:28 json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2024-11-12 22:04:18 Traceback (most recent call last):
2024-11-12 22:04:18   File "/usr/local/bin/uvicorn", line 8, in <module>
2024-11-12 22:04:18     sys.exit(main())
2024-11-12 22:04:18              ^^^^^^
2024-11-12 22:04:18   File "/usr/local/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
2024-11-12 22:04:18     return self.main(*args, **kwargs)
2024-11-12 22:04:18            ^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-12 22:04:18   File "/usr/local/lib/python3.12/site-packages/click/core.py", line 1078, in main
2024-11-12 22:04:18     rv = self.invoke(ctx)
2024-11-12 22:04:18          ^^^^^^^^^^^^^^^^
2024-11-12 22:04:18   File "/usr/local/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
2024-11-12 22:04:18     return ctx.invoke(self.callback, **ctx.params)
2024-11-12 22:04:18            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-12 22:04:18   File "/usr/local/lib/python3.12/site-packages/click/core.py", line 783, in invoke
2024-11-12 22:04:18     return __callback(*args, **kwargs)
2024-11-12 22:04:18            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-12 22:04:18   File "/usr/local/lib/python3.12/site-packages/uvicorn/main.py", line 412, in main
2024-11-12 22:04:18     run(
2024-11-12 22:04:18   File "/usr/local/lib/python3.12/site-packages/uvicorn/main.py", line 516, in run
2024-11-12 22:04:18     config = Config(
2024-11-12 22:04:18              ^^^^^^^
2024-11-12 22:04:18   File "/usr/local/lib/python3.12/site-packages/uvicorn/config.py", line 273, in __init__
2024-11-12 22:04:18     self.configure_logging()
2024-11-12 22:04:18   File "/usr/local/lib/python3.12/site-packages/uvicorn/config.py", line 368, in configure_logging
2024-11-12 22:04:18     loaded_config = json.load(file)
2024-11-12 22:04:18                     ^^^^^^^^^^^^^^^
2024-11-12 22:04:18   File "/usr/local/lib/python3.12/json/__init__.py", line 293, in load
2024-11-12 22:04:18     return loads(fp.read(),
2024-11-12 22:04:18            ^^^^^^^^^^^^^^^^
2024-11-12 22:04:18   File "/usr/local/lib/python3.12/json/__init__.py", line 346, in loads
2024-11-12 22:04:18     return _default_decoder.decode(s)
2024-11-12 22:04:18            ^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-12 22:04:18   File "/usr/local/lib/python3.12/json/decoder.py", line 337, in decode
2024-11-12 22:04:18     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
2024-11-12 22:04:18                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-12 22:04:18   File "/usr/local/lib/python3.12/json/decoder.py", line 355, in raw_decode
2024-11-12 22:04:18     raise JSONDecodeError("Expecting value", s, err.value) from None
2024-11-12 22:04:18 json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by simadimonyan** [comment]
I think this is due to last docker image  langgraph 3.12 commit on https://hub.docker.com/layers/langchain/langgraph-api/3.12/images/sha256-782d386ba91fcda0530a4f27d477f08eb2a180d3b1e63aeb28d1005b9749a452?context=explore
