### ISSUE TITLE
Windows version

### ISSUE THREAD

**Issue by mohamedfadlalla** [langchain-ai/langgraph-studio#63]
Do you have a plan for releasing it on windows

**Comment by accordaccount** [comment]
I would like to see it as well

**Comment by StuartJAtkinson** [comment]
Yeah or at least linux since that's also unix so should be easier and could then possbily be run with WSL functions

**Comment by Emad297** [comment]
Also looking forward to **windows** version.

**Comment by smitpatl** [comment]
I would also love to have a Windows version!

**Comment by junan-trustarc** [comment]
any estimated time to be released?

**Comment by Freffles** [comment]
Lack of windows support is frustrating 😞

**Comment by yale8848** [comment]
me too

**Comment by dqbd** [comment]
Hello, Windows support is still on our roadmap, but in the meantime, you can use the LangGraph CLI to run the debugger locally: `https://langchain-ai.github.io/langgraph/cloud/reference/cli/#up`

**Comment by junan-trustarc** [comment]
> Hello, Windows support is still on our roadmap, but in the meantime, you can use the LangGraph CLI to run the debugger locally: `https://langchain-ai.github.io/langgraph/cloud/reference/cli/#up`

Hi @dqbd,

langgraph up doesn't work as well.
Can you help to check why FileNotFoundError: [Errno 2] No such file or directory: '/deps/__outer_arc-ai-api/src/app\\graph.py' ?

```
arc-ai-api-langgraph-api-1       | 2024-10-01T19:23:46.281627Z [error    ] Traceback (most recent call last):  
arc-ai-api-langgraph-api-1       |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 693, in lifespan
arc-ai-api-langgraph-api-1       |     async with self.lifespan_context(app) as maybe_state:
arc-ai-api-langgraph-api-1       |   File "/usr/local/lib/python3.11/contextlib.py", line 210, in __aenter__   
arc-ai-api-langgraph-api-1       |     return await anext(self.gen)
arc-ai-api-langgraph-api-1       |            ^^^^^^^^^^^^^^^^^^^^^
arc-ai-api-langgraph-api-1       |   File "/api/langgraph_api/lifespan.py", line 23, in lifespan
arc-ai-api-langgraph-api-1       |   File "/api/langgraph_api/shared/graph.py", line 200, in collect_graphs_from_env
arc-ai-api-langgraph-api-1       |   File "/usr/local/lib/python3.11/site-packages/langchain_core/runnables/config.py", line 584, in run_in_executor
arc-ai-api-langgraph-api-1       |     return await asyncio.get_running_loop().run_in_executor(
arc-ai-api-langgraph-api-1       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
arc-ai-api-langgraph-api-1       |   File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
arc-ai-api-langgraph-api-1       |     result = self.fn(*self.args, **self.kwargs)
arc-ai-api-langgraph-api-1       |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
arc-ai-api-langgraph-api-1       |   File "/usr/local/lib/python3.11/site-packages/langchain_core/runnables/config.py", line 575, in wrapper
arc-ai-api-langgraph-api-1       |     return func(*args, **kwargs)
arc-ai-api-langgraph-api-1       |            ^^^^^^^^^^^^^^^^^^^^^
arc-ai-api-langgraph-api-1       |   File "/api/langgraph_api/shared/graph.py", line 228, in _graph_from_spec  
arc-ai-api-langgraph-api-1       |   File "<frozen importlib._bootstrap_external>", line 936, in exec_module   
arc-ai-api-langgraph-api-1       |   File "<frozen importlib._bootstrap_external>", line 1073, in get_code     
arc-ai-api-langgraph-api-1       |   File "<frozen importlib._bootstrap_external>", line 1130, in get_data     
arc-ai-api-langgraph-api-1       | FileNotFoundError: [Errno 2] No such file or directory: '/deps/__outer_arc-ai-api/src/app\\graph.py'
arc-ai-api-langgraph-api-1       |  [uvicorn.error] api_revision=0019c5d api_variant=licensed
arc-ai-api-langgraph-api-1       | 2024-10-01T19:23:46.281802Z [error    ] Application startup failed. Exiting. [uvicorn.error] api_revision=0019c5d api_variant=licensed
arc-ai-api-langgraph-api-1 exited with code 3
time="2024-10-01T15:15:12-04:00" level=warning msg="The \"line\" variable is not set. Defaulting to a blank string."
 Container arc-ai-api-langgraph-postgres-1  Created
 Container arc-ai-api-langgraph-redis-1  Created
 Container arc-ai-api-langgraph-api-1  Recreate
 Container arc-ai-api-langgraph-api-1  Recreated
arc-ai-api-langgraph-postgres-1  | 2024-10-01 19:23:37.712 UTC [1] LOG:  starting PostgreSQL 16.4 (Debian 16.4-1.pgdg120+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
arc-ai-api-langgraph-postgres-1  | 2024-10-01 19:23:37.712 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
arc-ai-api-langgraph-postgres-1  | 2024-10-01 19:23:37.712 UTC [1] LOG:  listening on IPv6 address "::", port 5432
arc-ai-api-langgraph-postgres-1  | 2024-10-01 19:23:37.717 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
arc-ai-api-langgraph-postgres-1  | 2024-10-01 19:23:37.722 UTC [29] LOG:  database system was shut down at 2024-09-23 23:35:13 UTC
arc-ai-api-langgraph-postgres-1  | 2024-10-01 19:23:37.733 UTC [1] LOG:  database system is ready to accept connections
Aborting on container exit...
 Container arc-ai-api-langgraph-api-1  Stopping
 Container arc-ai-api-langgraph-api-1  Stopped
 Container arc-ai-api-langgraph-redis-1  Stopping
 Container arc-ai-api-langgraph-postgres-1  Stopping
 Container arc-ai-api-langgraph-redis-1  Stopped
 Container arc-ai-api-langgraph-postgres-1  Stopped
```

**Comment by jhb96** [comment]
Any update?

**Comment by AMMISAIDFaical** [comment]
hello is there any update on the windows version

**Comment by humandotlearning** [comment]
petition to prioritise windows or linux app

**Comment by jhb96** [comment]
fyi

**Comment by Freffles** [comment]
> fyi, now you can get it directly in python as pip lib https://www.youtube.com/watch?v=o9CT5ohRHzY&ab_channel=LangChain

Excellent tip, thanks!

**Comment by hinthornw** [comment]
Hi all! As mentioned above and ([in the docs](https://langchain-ai.github.io/langgraph/how-tos/local-studio/), we now support a similar experience using the:

```shell
langgraph dev
```
command.

We don't have near-term plans to develop a desktop application for windows; instead we want to ensure we support the same functionality through the CLI + web UI.

**Comment by Freffles** [comment]
left this in the dust a long time ago 😒

**Comment by zcfrank1st** [comment]
+1

**Comment by dqbd** [comment]
LangGraph CLI supports JS and Python graphs alike and now supersedes the Desktop app! Read more here: https://langchain-ai.github.io/langgraph/cloud/reference/cli/
